# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('price', models.CharField(max_length=10)),
                ('picture', models.CharField(max_length=250)),
                ('rating', models.FloatField()),
                ('review_count', models.IntegerField()),
                ('delivery_time', models.TextField()),
                ('bullet_points', models.TextField()),
                ('details', models.TextField()),
            ],
        ),
    ]
