# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-07 17:12
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('url', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('price', models.CharField(max_length=10)),
                ('picture', models.CharField(max_length=250)),
                ('rating', models.FloatField()),
                ('review_count', models.IntegerField()),
                ('delivery_time', models.TextField(blank=True, null=True)),
                ('bullet_points', models.TextField(blank=True, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('promo', models.TextField(blank=True, null=True)),
                ('special', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity', models.IntegerField()),
                ('min_quantity', models.IntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.CharField(max_length=200)),
                ('is_new', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScrapyTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('mode', models.IntegerField(choices=[(1, 'Category'), (2, 'Products')])),
                ('status', models.IntegerField(choices=[(0, 'Finished'), (1, 'Running'), (2, 'Sleeping'), (3, 'Stopped')])),
                ('products', models.TextField(blank=True, null=True)),
                ('products_file', models.FileField(blank=True, null=True, upload_to=b'')),
                ('interval', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(5)], verbose_name='Interval (minutes)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Category')),
            ],
        ),
    ]
